### ISSUE TITLE
Unable to add the search as search engine in Firefox

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-iam/dino-park-issues#124]
**Environment:**
- Firefox Nightly 
- Ubuntu 16.04 LTS 

**Steps:**
- Open people.mozilla.org 
- Go to search engines bar and tap the + to add a new search engine

**Actual Result:**
- a pop up error is displayed and the search engine is not added

**Expected Result:**
- people.mozilla.org's search should be added to the search engines list

**Log:**
XML Parsing Error: mismatched tag. Expected: </link>.
Location: moz-nullprincipal:{5e2e62d6-81f5-49ed-a2d4-d0a2426aba43}
Line Number 55, Column 5: {5e2e62d6-81f5-49ed-a2d4-d0a2426aba43}:55:5
Invalid search plugin due to namespace not matching. SearchEngine.jsm:1184

![Screenshot from 2019-07-02 10-22-49](https://user-images.githubusercontent.com/1391451/60497198-077e9900-9cbd-11e9-8fc6-35921680070e.png)

**Comment by Standard8** [comment]
I took a brief look at this. On a fresh profile, if I log into people.mozilla.org, then try and add the search engine, I see a 307 redirect to https://people.mozilla.org/oauth/authorize. This redirects to https://auth.mozilla.auth0.com/authorize etc. That fails I think because i requires javascript.

If I subsequently load https://people.mozilla.org/opensearch.xml manually, I see the correct thing loaded straight away, and adding it to Firefox works.

I'm guessing opensearch.xml shouldn't really be behind authorisation since there's nothing sensitive in there.

**Comment by fiji-flo** [comment]
Indeed. Thanks for hunting this down. Should be deployed now.
