### ISSUE TITLE
New employee isn’t searchable on their first day

### ISSUE THREAD

**Issue by floatingatoll** [mozilla-iam/dino-park-issues#139]
Hi, a new employee’s was introduced to my division on Slack this morning. They’re present on old Phonebook right now with their Workday preferred name, but Dinopark isn’t able to find them at all. I assume this issue will be corrected after a 24 hour syncing interval passes; however, that creates an awkward experience for new
employees since they can’t be looked up by others (and may well encounter difficulty using the site and editing their profile). Please ensure that new staff are synced to Dinopark in a more timely manner.

**Comment by gdestuynder** [comment]
@floatingatoll Hi, can you msg or email me the name of the person ? (i.e. no on this ticket)
I'll double check to see if anything specific/wrong happened, or if we need to ask for these users to be added to HRIS/Workday a little ahead of time

otherwise, the system sync each 6 hours and respect HR attributes for when the profile is to be available. Phonebook does not respect HR attributes, so this can cause some differences. The 6 hour cadence is required by HRIS after many discussions on the subject

Thanks!

**Comment by gdestuynder** [comment]
Clarification per request: the attributes for staff were not present at time of user login, these were added a few hours later in the day (at which point the 6hr sync picked them up)
