### ISSUE TITLE
Heavily delayed navigation to org view highlight

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#140]
When navigating to a specific user in the org tree view, the sequence goes

* From a user's profile page click the org button
* The page refreshes taking the viewer to the org view
* 5 to 13 seconds later (on a super fast connection) the viewport updates to the highlighted user

It took me quite a while to realize that the highlight function wasn't just broken but instead delayed by a long period of time.

I suspect the cause of the problem is that the page rendering logic opts to try to draw every org users avatar image first before moving to the highlight anchor. Instead we should reverse those, move to the highlight, then render the avatar images.

I have an unlisted youtube video illustrating this that I'll send a link to (I don't want to post it here as it shows some of the people in our org and I'm not sure that's public info)

In my video, there is also an unexpected redirect from the org page back to the org page for some reason though I've not seen this every time (unlike the delay which I do).

**Comment by HerminaC** [comment]
Thanks for this, Gene! Please send us the video (me and Florian) via Slack. I'll bring this to him on Monday, when he's back.

**Comment by fiji-flo** [comment]
@gene1wood Thanks for reporting this and the video. I finally was able to spend the time to fix this. Should be fast now for that use case. I still need to debug this more. If you:

- reload
- go to orgchart
- click on expand all and quickly after click on a person

the issues is still there (since I fixed you case by lazy loading the pictures).

Anyhow. I'll report back once everything is smooth.
