### ISSUE TITLE
search seems to work too broadly when an exact match can be found

### ISSUE THREAD

**Issue by cshields** [mozilla-iam/dino-park-issues#143]
STR: search "ericz"

The right "ericz" does come up in the results, at the top (yay), and is a direct match on his username. However, the search returns 10 others with a form of "eric" in their name but no "ericz".

Should probably not search fuzzily if/when there's an exact match found.

**Comment by HerminaC** [comment]
Hey Corey,

On the other hand, if someone wants to search for someone called Eric but doesn't know exactly how is his name spelled or misspelles his name when typing (and writes Ericz for eg), I think that person would appreciate to not only see 1 result with his exact search, but multiple, so that he can cross check with the photo as well and find the person he's looking for. 
The fact that your exact search shows first I believe to be good enough for your case and the fact that similar results show below is good to cover for the case i described above. 

Hope this helps!

**Comment by cshields** [comment]
Understood - then I might change this to a feature request that matching strings appear and get highlighted in the search results.  Using the example above, if I search for "ericy" all eric* fuzzy results appear, but then searching for "ericz" would show the fuzzy results and under Eric Ziegenhorn's result show "Username: **ericz**  IRC **ericz** ... etc"

I'll note for anyone else who reads this, I just found that searching by @ericz in this case pulls up the only match that matters.

**Comment by cshields** [comment]
Another case here:  search 'chlin'..  there are 4 results returned, with the first 3 not having a match for the actual string - and the last one does (who is the real chlin, but he shows up last). 

And, given my last solution of @username, doesn't work here as chlin is the email address and he has not set a username so @chlin pulls up no results.

So - given this use case I want to keep this open as a real issue.  If there is an exact match of a string that should at least show up first and/or be highlighted such, not possibly buried to the bottom.
