### ISSUE TITLE
Integration with discourse doesn't seem to work.

### ISSUE THREAD

**Issue by dhylands** [mozilla-iam/dino-park-issues#153]
I also reported this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1578520 but I'm not sure that's the right place.

Everytime I visit discourse.mozilla.org, I get presented with a dialog titled "Discourse integrates with people.mozilla.org", even if I click the "Don't show this again" link.

Problem 1: I can't enter anything into any of the fields. The mouse changes to a circle with a slash through it.

f I go to the bottom of the dialog and click the "I agree" checkbox, then the "Yes, find and link my profile" button becomes active and if I click it, then it populates the "Username" field with dhylands, and then changes to "Confirm and link account".

Problem 2: If I click "Confirm and link account" then I get a spinny circle for a bit and then it goes back to the first dialog.

Clicking the X at the top right, "Not right now" or "Don't show this again" all dismiss the dialog, and the dialog reappears the next time I browse to discourse.mozilla.org

I'm using Firefox 68.0.2 running under ubuntu.

**Comment by LeoMcA** [comment]
This is an odd bug, my only idea is that the `authentication_data` cookie isn't being deleted because I didn't specify the path.

I've done that in https://github.com/mozilla/discourse-mozilla-iam/commit/c419042277d574c2863563a92d704c8d1a8a5131 which has been deployed to prod.

@dhylands can you let me know if you still see the bug? And if so, can you send a screenshot of the cookie names and paths you see in DevTools under the "Storage" tab, like so:

![Screenshot from 2019-09-04 15-31-00](https://user-images.githubusercontent.com/755354/64334995-bf883500-cfd1-11e9-9372-f82288c4131e.png)

**Comment by dhylands** [comment]
As of this morning, I no longer get the dialog.
