### ISSUE TITLE
Allow a user to restrict workday information from NDA's

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/dino-park-issues#157]
Currently my job title, office location, desk number, and team are visible to 'NDA + Staff'.

Non-staff folk do not need that information on me, and I'd like to have the option to restrict as much as possible to staff-only.

**Comment by HerminaC** [comment]
Hi @gcoxmoz,

Sorry for the late reply on this - i took some time thinking about what you're asking as I've also consulted with different people within Mozilla. All this to say that I see your point and I carefully considered it. 
Mozilla is a company with an unique NDA - it's not staff only, it's staff and volunteers and partners (like universities, research agencies...). We work together on topics of interest for all, on things that will sometimes change the status quo or on things that no other company would have an interest to put resources into. 
Because of this, 3 years ago we've decided we needed a tool that will help us collaborate. We needed easier access to information and we needed to empower different communities (paid or not) to work towards the same goal. Hence the approach to merge Phonebook and Mozillians.org (a volunteer tool) into people.mozilla.org and to actually make them better.

Unfotunately, what you mention above - 'I want to restrict as much as possible to staff-only', defeats the purpose of this entire effort. I'd like to ask for your help so that we open up as much as each one of us is comfortable with towards our broader communities. 

This being said, it's obviously your choice on what you want to share and with whom - and you have the option on the vast majority of the fields. The few ones where you cannot, get imported directly from Workday and that's why they are not editable. We have the same default visibility for them as for the other fields because we believe that an NDA'd contributor (who signed a non disclosure agreement with us anyway) needs to know someone's official title and office location (as bare minimum) in order to be able to have a meaningful collaboration with that person (eg: it would be pretty relevant to me to know if an engineer is front end..back end etc when asking him for help on a certain task, or what's his team - if my question concerns a certain product, or what's his timezone in order to meet etc etc). 

All in all, the default will remain as is for the time being but in case we will have specific situations that will request us to reconsider, we are happy to look into those on a case by case basis. 

Thanks!
Hermina
