### ISSUE TITLE
Editing Profile: Weird UX with default display level selection

### ISSUE THREAD

**Issue by jens1o** [mozilla-iam/dino-park-issues#167]
I find it confusing that by default as an NDA'd volunteer the preselection defaults to `Staff` only for new content when editing your own profile. Rather, I'd expect it to be `Private`.

**Comment by LeoMcA** [comment]
`Private` is a bit of a misnomer because it's still accessible to privileged members of staff or services (the data has to be stored somewhere!). If you notice, you shouldn't be able to set anything to `Private` via the dropdown unless it's already set to `Private` (which would have been set by default).

@HerminaC I believe I remember a discussion around setting the default for NDA'd volunteers to `NDA'd`, but we decided against it?
