### ISSUE TITLE
Editing profile: Cannot override timezone

### ISSUE THREAD

**Issue by jens1o** [mozilla-iam/dino-park-issues#170]
For example, I want to anonymize my real location, which is why I only enter a rough location, like `Europe`.

Now, Europe consists of some different timezones, which is why it might be useful to manually set a timezone.

**Comment by LeoMcA** [comment]
I believe this feature was added to make editing your timezones easier (so you could just edit your location, and didn't need to know the associated timezone code), but yes I agree that its odd you're not able to override it if you want.

@HerminaC this seems like a bug, did we actually want to lock-down timezone editing when linking it to location?

**Comment by HerminaC** [comment]
Hey @LeoMcA,

It's expected behaviour - anyone can choose not to share their location if they don't want to, but this impacts the timezone info. They are linked for convenience of use mainly and they also impact the way employees are scheduling meetings because of the time auto-converting feature we have associated to it, hence we want this info the be reliable. 
@jens1o we have plenty of fields that we purposely made to allow free text, so that people can add specific info in there. I would suggest you use the Bio for making this info available for eg. 

Thx,
Hermina
