### ISSUE TITLE
`Verify` button under identities tab doesn't make much sense

### ISSUE THREAD

**Issue by devcer** [mozilla-iam/dino-park-issues#171]
-> Clicked on `Add Identity` in identities tab
-> Clicked on `verify` button after selecting github
-> The screen is redirected to Authorize my github account

The name of the button `verify` is actually ambigious as it actually authorizes my github account rather than verifying if my details are correct or not. `Authorize` makes more sense.

**Comment by LeoMcA** [comment]
Thanks for the feedback @devcer,

"Verify" is language used across the UI (the accounts are listed as verified once you've added them, for instance), and I believe it was chosen because of its relative non-technicalness (compared to "authorize").

Would you agree that if you've *authorized* your github account, then the fact that you have access to that github account has been *verified*?

**Comment by devcer** [comment]
Makes sense. thanks. :)
