### ISSUE TITLE
Unable to reach my own phonebook entry

### ISSUE THREAD

**Issue by gcoxmoz** [mozilla-iam/dino-park-issues#180]
https://people.mozilla.org/s?query=gcox&who=all - This used to list just me, now it lists me, an admin account of mine, and James Cox.  Bit of a change, but not a bug.

If you click on me, https://people.mozilla.org/p/gcox , it comes up as 'This page isn't available'.

**Comment by gdestuynder** [comment]
the first behavior is normal, as these accounts are now imported in the system
the second behavior is not normal and I think i traced down what happened:

- aws account ran out of global throughput (requestlimit for the account reached)
- import function ran, but failed a few things including opening a new log stream, due to the threshold
- import function failed to query the profile from dynamodb (in this case gcox's profile)
- code incorrectly report this to log then return no item found, instead of breaking there and retuning a failure
- caller of this code sees no item returned, i.e. there was no user
- brand new user is provisioned, overwriting old user

**Comment by gdestuynder** [comment]
your profile has been restored (all other affected profiles were restored)

thanks for the quick report and ping, much appreciated. The actual fix for this will land soon in mozilla-iam/cis

**Comment by gcoxmoz** [comment]
Thanks for the investigation and restoration!
