### ISSUE TITLE
View in Org Chart: Show org chart highlight somewhat centered

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#27]
**Step 1:** Click _view in org chart_
<img width="665" alt="search result page for hmitsch, shows one result, result has view in org chart button" src="https://user-images.githubusercontent.com/869692/49439213-73803980-f78e-11e8-997e-6974cbeb76e4.png">

**Current result:** Person highlighted at the bottom of the screen
<img width="579" alt="shows person highlighted at bottom of screen, with URL preview overlaying the person, so that their job title is obfuscated" src="https://user-images.githubusercontent.com/869692/49439254-8dba1780-f78e-11e8-8171-00f32b2e4938.png">

**Desired result:** Show that highlight "somewhat centered" or at least a few more pixels from the bottom

**Comment by hidde** [comment]
(edited issue to have alternative text)

**Comment by hidde** [comment]
This is now fixed in prod. 

The fix uses an argument for `scrollIntoView` that Safari and some other browsers don't understand, we're fixing that here: https://github.com/mozilla-iam/dino-park-front-end/pull/161 by giving those browsers the behavior we had (align highlighted person to bottom of viewport).
