### ISSUE TITLE
Hoverstatus for clickable links

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#30]
(from All Hands Demo)

Some things in a profile are clickable and become search queries (e.g. officeLocation). We got user feedback, that it is not clear that these things are clickable. Do we want to change things in any way or keep them as is?

/cc @mbransn

**Comment by hidde** [comment]
For the record, these are my thoughts: as a general rule, links should be distinguishable (blue and underline is awesome), but in this specific case, I think it is ideal if we require users to ‘learn’ they exist. The only (I admit, super subtle) hint is the hand cursor and the URL preview tooltip. I would recommend not changing this and not making them look like links, because if we do that, we may end up with lots of stuff on the page that looks like links.

These are my two cents, I would love @mbransn's ideas on this.

**Comment by mbransn** [comment]
@hidde for these type of links, how about a blue hover state. I believe we have this styling in the experience elsewhere, but perhaps not implemented yet (filter `cancel` comes to mind). I agree we do not desire to overburden cognitive load by peppering the experience with blue links throughout. A bit of discovery is a good thing, aiding that discovery with confirmation on hover would be good. Touch devices would ideally replicate this blue/underline on active state. cc @rfirebaugh

**Comment by hidde** [comment]
Oh I love that suggestion (blue on hover).

**Comment by hidde** [comment]
I found we also have the blue hover on the Show More button, so this is pretty consistent.

This is what I've implemented:

* hover for cancel button in search field (thanks @mbransn, I forgot about that one) 
* hove states for links in profile
