### ISSUE TITLE
Should bulk pandoc from wiki markup to markdown for bio field

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#58]
The current content of the bio field is encoded in [wiki markup](http://en.wikipedia.org/wiki/Help:Wikitext_examples). (See phonebook that says " Links in wiki markup style supported. " in the bio section)

Dinopark doesn't render wiki markup but does render markdown.

We should do a one time bulk conversion of all bio fields from wiki markup to markdown (e.g. using [pandoc](https://pandoc.org/)) so that we don't break everyone's markup in all profiles bio fields

**Comment by hmitsch** [comment]
Hi @gene1wood, thanks for the engagement. This is awesome.

In an ideal world, I agree with you. Our main challenge currently is that we are very short of development capacity. For this reason, I would hold off from investing energy into a conversion.

As we migrate to the new People Directory, we kindly request people to add their profile picture. We did not migrate the photo, because this allows us to level set the data classification.

A similar approach could apply to the `bio` field. We imported its content, and we ask you to review and update it. At the same time, markup could be manually moved from Wiki Markup to markdown.

What do you think about this?

**Comment by gene1wood** [comment]
That sounds fine. With the people API though I suspect it's about 5 lines of code to
* iterate over all profiles
  * for each profile read the bio field
  * run pandoc against it to convert to markdown
  * write back to the bio field

**Comment by hmitsch** [comment]
@gene1wood, if you have time to do it, we would all be thrilled!!

I don't want to approach Florian, kang or Andrew with this at the moment because they are working hard towards "_Edit Mode_ beta audience readiness".

**Comment by gdestuynder** [comment]
if we did do this, we should do it before its available to all staff. otherwise, we should tell people about the possibility to convert manually to markdown at least.

note: its possible to do this with the CIS API directly so PR's/scripts welcome of course ;-)
