### ISSUE TITLE
Subjective : "Ping Me" text possibly confusing

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#64]
In the "Contact me" drop down the text next to the Slack contact option says

`Ping Me`

Though this is a common phrase used internally in Mozilla, I'm unsure if the general public and Mozillians in general know that this means "Chat with me". I think our use of "ping" in Mozilla and possibly more broadly in technical fields derives from the [ping network utility](https://en.wikipedia.org/wiki/Ping_(networking_utility)).

Perhaps we should change this to something easier to understand by everyone like "chat"?

**Comment by mbransn** [comment]
Hmm, this escaped my attention and I do agree.

@HerminaC ideally these would be labeled as what they are: 'Email' 'Slack' 'Phone' No need IMO to keep up the 'Contact Me' CTA context in the dropdown itself.

cc @hidde @hmitsch

**Comment by hmitsch** [comment]
Jira copy at https://jira.mozilla.com/browse/DP-1290 (Sorry, access restricted)

**Comment by HerminaC** [comment]
(Don't worry, Henrik, replying here as well)

Thanks Gene, I do think this is subjective. 'Ping me' is broadly used inside/outside Mozilla.  
The way it is currently displayed under 'Contact me' in DP (Ping me 'usename' on Slack) also seems self explanatory to me. For the time being I wouldn't change it, I am happy to reconsider though in case we'll get more feedback like this.

**Comment by mbransn** [comment]
Hi all FWIW the original design did not include any labels in order to keep the dropdown light and less cumbersome -- [possible to get back to that](https://overflow.io/s/3YX3BV/?node=c80656f1)?

![contact-me-design](https://user-images.githubusercontent.com/18686986/57495065-2fcfb580-7281-11e9-85ec-e00181561165.png)

@HerminaC

**Comment by hidde** [comment]
This is now updated to match the original designs, so that we have just icons and accounts (, phone numbers, email addresses, etc). The update is deployed to our dev and test environments.

**Comment by mbransn** [comment]
@hidde I've noticed that the email icon is an `@` rather than an [mail icon](https://zpl.io/29wPORd) and the phone icon uses an additional arrow version rather than just the [phone](https://zpl.io/VKD1L1A). Can you update both of those to match the icons in the screenshot above? Slack and IRC icons are correct though! :)

**Comment by hidde** [comment]
No problem, I have added an issue in Jira for this (DP-1362)
