### ISSUE TITLE
At first login, identicon was not clearly the place to go for profile updates 

### ISSUE THREAD

**Issue by alanmoo** [mozilla-iam/dino-park-issues#66]
Low priority, I'm sure, but I feel like I should give this feedback:

When I first logged in, I was trying to figure out where to go in order to update my profile, as suggested in the email that went out to beta users. The purpose of the org chart button nor the identicon I was given were immediately obvious, I only guessed out that the identicon was to get to my profile by its placement and trial/error. At a minimum, having a title attribute on that button might be helpful for desktop users.

(Once I saw the list of other users and their identicons, the system made sense, and I liked the variance of them.)

**Comment by hmitsch** [comment]
Pinging @mbransn on this for visbility.

**Comment by mbransn** [comment]
Thanks @hmitsch -- @alanmoo this is great feedback and the type of wayfinding we're 'testing' with this beta. Agreed that a title attribute would be very helpful, @hidde is this something we've considered? esp from an accessibility perspective?

As for these button uses not being immediately obvious, a bit of trial/error is expected as new mental models are formed. A bit of onboarding could be helpful as well though when we go to a full release to aid in initial wayfinding. cc @HerminaC for feature consideration in the roadmap (it is one UX advocates)

**Comment by hmitsch** [comment]
Jira copy at https://jira.mozilla.com/browse/DP-1291 (sorry, access restricted)

**Comment by HerminaC** [comment]
Hey @alanmoo,

Thx for this. Would having the editing pencil on the identicon have helped you?  Something like this:
<img width="145" alt="Screen Shot 2019-04-29 at 11 30 19 AM" src="https://user-images.githubusercontent.com/7406447/56887572-451f3580-6a72-11e9-8eef-431537752597.png">


Hermina

**Comment by alanmoo** [comment]
Yeah, I think it may have.

**Comment by hidde** [comment]
@mbransn To give a bit of insight in the accessibility treatment of the user menu: the avatar that opens the user menu (technically a _button_) does have an [accessible name](https://hiddedevries.nl/en/blog/2019-04-18-naming-things-to-improve-accessibility) (a text that describes it): _Open user menu_ (when opened, _Close user menu_). People with screenreaders will hear that when they get to the button, so that everyone gets info on what the button does.

We don't expose this visually, but we could (perhaps should), for example in a tooltip that is shown on hover and keyboard focus, I'm thinking something like this (from Jira):

<img width="110" alt="Icon with descriptive tooltip" src="https://user-images.githubusercontent.com/178782/56899173-1e252b80-6a93-11e9-8ee2-1c77ade25813.png">

This would not make it clear that this is where “My profile” lives or that that is the place to edit one's profile, but at least it would clarify what clicking on the avatar does.

**Comment by mbransn** [comment]
Hi y'all, thanks for the feedback & discussion. If it's strongly felt that we need a 'quick' change on this, I'd recommend an update to the menu (see below) and a simplified tooltip addition as @hidde mentioned.

![menu-alt](https://user-images.githubusercontent.com/18686986/56935003-60eeff80-6aa3-11e9-9fb0-1fc12a405d09.png)

This current menu method was chosen as it optimizes the impact of the menu across devices and is a common heuristic across web and app properties (social platforms to e-commerce). The menu was remote user tested during our initial release with success. I'm not in favor of adding a pencil icon on top of the avatar as this is a global menu, not just a way to navigate to the profile for editing.

With the addition of today's profile editing functionality, I'd advocate for gathering more feedback during the beta period and running a remote user test for the profile editing capability itself (this would require us to set up a dummy test account, but is achievable). As mentioned previously, more context through an onboarding flow may be most helpful for all profile owners, whether staff or volunteer contributors. Only with data can we round out our subjective ideas and make a sound decision. :)
