### ISSUE TITLE
Verify that default display setting for primary email address is set to staff

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#72]
Currently I'm able to view primary email addresses for contributors in Dinopark which I'm unable to see in either phonebook or mozillians.org. Examples

* https://people.mozilla.org/p/r--AY4uJFt_WaekHJaAjUYLTg==
* https://people.mozilla.org/p/r--n6J7dd_hXqm-7Go1u8nlSA==

I would assume that this might be surprising to these users that their email address was viewable now though it wasn't in the past.

As only staff currently have access to Dinopark at the moment I'm not sure if these email addresses are visible to me because I'm staff or if they'd also be visible were I a contributor

Can we verify that this field, primary_email, which I can see for these users, wouldn't be visible to me were I a contributor trying to view them?

**Comment by hmitsch** [comment]
@gdestuynder what's your thinking of this? @gene1wood refers to the Contributor LDAP accounts which are treated by our import in the same way as Staff LDAP accounts and therefore get "minimum visbility" set to `Staff only`.

**Comment by gdestuynder** [comment]
we can accommodate defaults for this (ie these can be set differently), but i think i'd ask someone like Lucy or Catlee about it - since these are special contributor accounts which used to be created for their staff-like properties.

Note that in this case its email and name(s) that are default to "staff" `display` not just email.
