### ISSUE TITLE
add bugzilla.mozilla.org as an account

### ISSUE THREAD

**Issue by globau** [mozilla-iam/dino-park-issues#80]
I see that I can add "Mozilla Slack" and "IRC", but not "bugzilla.mozilla.org".
Having BMO in the mix would be _super_ useful.

If added please be aware that developers interact with multiple Bugzilla installations, so the account for our install should be identified as Mozilla's.

**Comment by hmitsch** [comment]
Hi again,

totally agree and thanks for this improvement suggestion.

For systems such as Github and Bugzilla we think of them as "identities" rather than "accounts". The main reason being that we need verified links for these systems. This will allow us to provide verified identities for LDAP, Github, Bugzilla (and maybe others) via the Profile API. Very useful to triangulate users in Phabricator and other places.

Unfortunately the "identities" section is not ready yet. It's on our backlog and we will get to it in the future.

Best regards,
   Henrik

**Comment by globau** [comment]
that's a shame, because the BMO email address is present on the current phonebook; losing it is likely to be problematic.

**Comment by hmitsch** [comment]
CC'ing in @HerminaC. We probably just identified a scope gap on the path to our _Phonebook Replacement_ milestone.

**Comment by fiji-flo** [comment]
Verified bmo accounts are now supported ( via the identities section ).

**Comment by globau** [comment]
\o/ thank you!
