### ISSUE TITLE
Two/Three spinners showing upon page load

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/dino-park-issues#9]
Open org chart view. Two spinners are on that page:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/869692/48809080-76f1da80-ed23-11e8-8a1a-3d48b276297d.png">

**Comment by hidde** [comment]
This is because we are loading 3 things, they can finish loading at different times.

If we want to fix it, we probably want to make 'loading' a global thing, as in, if one component is loading something, we consider the whole interface to be 'loading'. I think that's not good, because often other parts of the interface are usable if a thing is loading. I'd prefer components to have their own loading states.

With that in mind, do we want to fix this?

**Comment by hmitsch** [comment]
@mbransn, your call. :-)

**Comment by mbransn** [comment]
One spinner please, three looks quite broken to those who don't know what's happening behind the scenes. @hidde is it possible to allow content to load in as it's ready, even though we only display one spinner?

**Comment by hmitsch** [comment]
New idea on how to transform this "annoyance" into a feature: We will write a text, describing what each spinner is actually doing:
* Loading people ...
* Loading org chart ...
* Loading ...

**Comment by mbransn** [comment]
I'm not sure we want load times to take long enough for this type of text to display.

@hidde I still have the same question as above: "is it possible to allow content to load in as it's ready, even though we only display one spinner?"

**Comment by hidde** [comment]
@mbransn It is possible to show only one, but which one should we then show?

**Comment by mbransn** [comment]
@hidde a perceived single loader; is it possible to create a hierarchy that prioritizes what gets loaded and presented first while other secondary and tertiary, heavier content is still loading in the background? G-Drive seems to do this now that I think about it, though I have no idea how it's achieved.

Also, this is not a top priority issue for me. Something we can continue to work through.

**Comment by hmitsch** [comment]
We did some improvements in December. I think we are done here.

-Henrik
