### ISSUE TITLE
Not possible to change primary email address to another @mozilla.com address

### ISSUE THREAD

**Issue by smaug----** [mozilla-iam/dino-park-issues#94]
(see the title)

**Comment by gdestuynder** [comment]
Currently, if you need to change your staff email you can do so by asking HR, as this is an invasive change with consequences (some systems will identify you by email and forget who you are when you do this)- but it's definitely possible

**Comment by smaug----** [comment]
Many people have aliases to their email addresses, often because they prefer some other address than the default one.

**Comment by gdestuynder** [comment]
The LDAP addresses are provided as a convenience/favor, but not the official work address.
In order to change your official work email you would have to do so with HR in Workday - when that's done it will be reflected in Dinopark automatically. I would recommend doing so if you would prefer a specific, different email to be used consistently.

If not, the feature itself is currently at https://jira.mozilla.com/browse/IAM-168 and will be backlogged for now

That being said, there is another task in order to be able to add additional email aliases to your profile, which is tracked at https://jira.mozilla.com/browse/IAM-164 and will normally be implemented, and is a required step in this direction anyway (i understand that this is a closed IT system, its unfortunate - if you have access though, this is where the work is tracked)
